main: org.china2b2t.azurmgr.Main
name: AzurMgr
version: 1.0
author: [ Rabbit0w0 , lushangkan ]
api-version: 1.12
commands:
  pluginmgr:
    description: Plugin Manager
    aliases: [pl, plm]
  genkey:
    description: Generate a master key
    aliases: [gkey, keygen]
  kill:
    description: Suicide
  azurload:
    description: Reload
    aliases:
      - aload
      - azl
      - al
      - azload